"""Renamed Fields in Material Table

Revision ID: 15ce45e2b807
Revises: cee3b25a5b97
Create Date: 2024-04-08 14:51:13.232891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ce45e2b807'
down_revision = 'cee3b25a5b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index related to inventory_code, replace 'index_name' with the actual index name
    op.drop_constraint('UQ__material__86FEB279ED9F597E', 'material',  type_='unique')
    op.drop_constraint('UQ__material__098FE107C406ACF3', 'material',  type_='unique')
    
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jpdm_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sap_print_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mw_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wst_code', sa.String(length=50), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               nullable=True)
        batch_op.alter_column('material_type',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)

        batch_op.drop_column('inventory_code')
        batch_op.drop_column('sap_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_code', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inventory_code', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('material_type',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               nullable=False)
        batch_op.drop_column('wst_code')
        batch_op.drop_column('mw_code')
        batch_op.drop_column('sap_print_number')
        batch_op.drop_column('jpdm_number')

    # ### end Alembic commands ###
