"""Material Number from str to int

Revision ID: 2034b87e3ca3
Revises: 15ce45e2b807
Create Date: 2024-04-08 15:23:41.786650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2034b87e3ca3'
down_revision = '15ce45e2b807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('material_number',
               existing_type=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('material_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
