"""Remove time-related fields from MaterialSystem

Revision ID: cee3b25a5b97
Revises: 33208a9a54cd
Create Date: 2024-03-28 14:28:55.735525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'cee3b25a5b97'
down_revision = '33208a9a54cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('material_system', schema=None) as batch_op:
        batch_op.drop_constraint('FK__material___date___628FA481', type_='foreignkey')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('date_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__material___date___628FA481', 'date_table', ['date_id'], ['id'])

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B6168909B37')
    )
    # ### end Alembic commands ###
